"""Assemble the indented SVG. Animation is CSS inside the file."""

from xml.sax.saxutils import escape

from header import config as C
from header.contributions import load
from header.css import cube_css, letter_css, snake_css
from header.eater import eat_path, eat_times, step_times
from header.glyphs import glyphs
from header.timeline import eat_start


def plan(source, rng):
    fills = load(source, rng)
    path = eat_path(list(fills), rng)
    times = step_times(path, rng)
    eaten = eat_times(path, fills, times)
    total = times[-1] + 0.6 if times else eat_start() + 0.6
    return fills, path, times, eaten, total


def build(preview=None, source="simulated", rng=None):
    if rng is None:
        raise ValueError("rng is required")
    fills, path, times, eaten, total = plan(source, rng)
    letters = glyphs()

    css = [
        "    text { font-family: Menlo, 'SF Mono', Monaco, ui-monospace, monospace; }",
        "    .s0, .s1, .s2, .s3 { transform-box: fill-box; transform-origin: 0 0; }",
    ]
    if preview is None:
        for g in letters:
            css.append(letter_css(g, total).rstrip())

    cube_class = {}
    idx = 0
    for cell, (at_s, color) in sorted(fills.items()):
        cube_class[cell] = ("C%d" % idx, color)
        if preview is None:
            css.append(cube_css(idx, at_s, eaten[cell], color, total).rstrip())
        idx += 1

    if preview is None and path:
        for lag, (name, _dim, _rx) in enumerate(C.SNAKE_PARTS):
            css.append(snake_css(path, times, total, lag=lag, name=name).rstrip())

    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" '
        'viewBox="0 0 %d %d" role="img" '
        'aria-label="hi there! welcome to seb\'s portfolio">'
        % (C.W, C.H, C.W, C.H),
        "  <!-- generated by header/ — python3 scripts/build_header.py -->",
        "  <style>",
        *css,
        "  </style>",
        '  <rect x="1" y="1" width="%d" height="%d" rx="8" '
        'fill="%s" stroke="%s" stroke-width="1"/>'
        % (C.W - 2, C.H - 2, C.CARD, C.BORDER),
        '  <g id="letters">',
    ]

    if preview != "cubes":
        for g in letters:
            cls = "glyph" if preview else "glyph L%d" % g["index"]
            lines.append(
                '    <text class="%s" x="%.1f" y="%.1f" '
                'text-anchor="start" dominant-baseline="middle" '
                'font-size="%s" fill="%s" opacity="%.2f">%s</text>'
                % (
                    cls,
                    g["x"],
                    g["y"],
                    g["size"],
                    g["fill"],
                    C.REST,
                    escape(g["ch"]),
                )
            )
    lines.append("  </g>")
    lines.append('  <g id="grid">')

    for r in range(C.ROWS):
        for c in range(C.COLS):
            if not C.cell_exists(c, r):
                continue
            x = C.OX + c * C.PITCH
            y = C.OY + r * C.PITCH
            event = cube_class.get((c, r))
            if preview == "cubes" and event:
                lines.append(
                    '    <rect x="%.1f" y="%.1f" width="%d" height="%d" '
                    'rx="%s" fill="%s" fill-opacity="1" '
                    'stroke="%s" stroke-width="0.8"/>'
                    % (x, y, C.SIZE, C.SIZE, C.RX, event[1], C.CUBE_STROKE)
                )
                continue
            cls = ' class="%s"' % event[0] if (preview is None and event) else ""
            lines.append(
                '    <rect%s x="%.1f" y="%.1f" width="%d" height="%d" '
                'rx="%s" fill="%s" fill-opacity="%.2f" '
                'stroke="%s" stroke-opacity="%.2f" stroke-width="0.8"/>'
                % (
                    cls,
                    x,
                    y,
                    C.SIZE,
                    C.SIZE,
                    C.RX,
                    C.CUBE,
                    C.CUBE_OPACITY,
                    C.CUBE_STROKE,
                    C.CUBE_STROKE_OPACITY,
                )
            )
    lines.append("  </g>")

    if preview is None:
        lines.append('  <g id="snake">')
        for name, dim, rx in C.SNAKE_PARTS:
            off = (C.SIZE - dim) / 2.0
            lines.append(
                '    <rect class="%s" x="%.2f" y="%.2f" width="%.1f" height="%.1f" '
                'rx="%.1f" ry="%.1f" fill="%s" opacity="0"/>'
                % (name, off, off, dim, dim, rx, rx, C.SNAKE)
            )
        lines.append("  </g>")

    lines.append("</svg>")
    lines.append("")
    return "\n".join(lines)


def write(svg):
    C.OUT.write_text(svg)
    return C.OUT
